# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

# ebuild generated by hackport 0.6.4

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Amateur astronomical computations"
HOMEPAGE="https://github.com/aligusnet/astro"
SRC_URI="https://hackage.haskell.org/package/${P}/${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"
IUSE=""

RDEPEND=">=dev-haskell/matrix-0.3.4.4:=[profile?]
	>=dev-lang/ghc-7.8.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-1.18.1.3
	test? ( >=dev-haskell/hunit-1.3.1.1
		>=dev-haskell/quickcheck-2.8.2
		>=dev-haskell/test-framework-0.8.1.1
		>=dev-haskell/test-framework-hunit-0.3.0.2
		>=dev-haskell/test-framework-quickcheck2-0.3.0.3 )
"
